apiVersion: kubeprober.erda.cloud/v1
kind: Probe
metadata:
  name: node
  namespace: kubeprober
spec:
  policy:
    # unit: minute
    runInterval: 30
  template:
    containers:
      - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        name: k8s
        image: kubeprober/probe-node:v0.1.0
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
    restartPolicy: Never
